[package]
name = "ds1621"
version = "0.1.0"
edition = "2021"
description = "Platform-agnostic Rust driver for the DS1621 I2C temperature digital sensor."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.7"
